FROM python:3.12

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV TF_ENABLE_ONEDNN_OPTS=0

EXPOSE 5000

CMD [ "flask", "run", "--host=0.0.0.0", "--port=5000" ]
